### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by ierpe** [bostondv/ultimate-posts-widget#19]
When the widget is called on a page where the loop is empty (for example a category page where the category does not contain any article), I get this notice :
```
Notice: Trying to get property of non-object in plugins/ultimate-posts-widget/ultimate-posts-widget.php on line 84
```
Changing the line 84 to : 
```

      if(isset($post)) $current_post_id =  $post->ID;
      else $current_post_id = 0;
```
solved the problem for me

**Comment by bostondv** [comment]
Fixed in https://github.com/bostondv/ultimate-posts-widget/commit/249505a6f8c0d92530121ec1ac4b5c7fc0ccddd7
