### ISSUE TITLE
Show posts only from current tag - for Pages

### ISSUE THREAD

**Issue by veracompadriatics** [bostondv/ultimate-posts-widget#26]
Hi,

just a minor issue I noticed: when tags are enabled for Pages in Wordpress (by default, only posts can be tagged in Wordpress), the checkbox option "Show posts only from current tag" is not working as expected.
That is because of the "is_single()" check in ultimate-posts-widget.php on line 134:
if ($attag && is_single()) {
which checks only for posts and not for pages.
I made the following change so the checkbox option above works both for posts and pages:
 if ($attag && (is_single() || is_page())) {

Can you include this minor modification into the code?

Thanks!

**Comment by bostondv** [comment]
Sounds like a good idea, would you be able to open a pull request? Thanks

**Comment by bostondv** [comment]
Implemented in this commit: https://github.com/bostondv/ultimate-posts-widget/commit/7ead68e617dd82779466344cb597bfa8cb7ce4de

**Comment by veracompadriatics** [comment]
Great thanks!
